
//property type list for dropdown filter
const datacategoryList = [
  "House", "Cottage", "Lounge", "Motel", "Hostel", "Hotel", "Apartment", "Villa", "Farm House"
]

const category = () => {
  const categoryList = [];
  for (let i = 0; i < datacategoryList.length; i++) {
    const element = { id: i + 1, checked: false, label: datacategoryList[i], }
    categoryList.push(element);
  }
  return categoryList
}

export const categoryList = category();


//location list for dropdown filter


export const datalocation = [
  "India", "Canada", "Australia", "Germany", "Japan", "United States", "France"
]

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
];



export const dataList = [
  {
    id: 1,
    title: "Holdlamis",
    noodbed: 2,
    bathroom: 1,
    area: 24,
    avaible: true,
    county: "United States",
    address: "08 Ridge Oak Pass",
    category: "Lounge",
    coverSrc: "/images/places/15.jpg",
    rating: 1,
    price: 4869
  },
  {
    id: 2,
    title: "Hatity",
    noodbed: 3,
    bathroom: 2,
    area: 21,
    avaible: true,
    county: "Australia",
    address: "166 Clove Trail",
    category: "Hotel",
    coverSrc: "/images/places/37.jpg",
    rating: 5,
    price: 2785
  },
  {
    id: 3,
    title: "Biodex",
    noodbed: 1,
    bathroom: 2,
    area: 17,
    avaible: true,
    county: "India",
    address: "24 Quincy Parkway",
    category: "Motel",
    coverSrc: "/images/places/43.jpg",
    rating: 2,
    price: 4010
  },
  {
    id: 4,
    title: "Prodder",
    noodbed: 3,
    bathroom: 2,
    area: 78,
    avaible: true,
    county: "Canada",
    address: "828 Elgar Parkway",
    category: "House",
    coverSrc: "/images/places/28.jpg",
    rating: 3,
    price: 4919
  },
  {
    id: 5,
    title: "Greenlam",
    noodbed: 1,
    bathroom: 2,
    area: 25,
    avaible: false,
    county: "Japan",
    address: "253 Schlimgen Trail",
    category: "Motel",
    coverSrc: "/images/places/27.jpg",
    rating: 2,
    price: 3298
  },
  {
    id: 6,
    title: "Pannier",
    noodbed: 4,
    bathroom: 1,
    area: 77,
    avaible: false,
    county: "India",
    address: "87 8th Center",
    category: "Villa",
    coverSrc: "/images/places/20.jpg",
    rating: 3,
    price: 3378
  },
  {
    id: 7,
    title: "Cookley",
    noodbed: 3,
    bathroom: 2,
    area: 36,
    avaible: false,
    county: "Germany",
    address: "11 Macpherson Street",
    category: "Hotel",
    coverSrc: "/images/places/6.jpg",
    rating: 2,
    price: 1279
  },
  {
    id: 8,
    title: "Alphazap",
    noodbed: 3,
    bathroom: 2,
    area: 46,
    avaible: true,
    county: "Germany",
    address: "95585 Mifflin Court",
    category: "Cottage",
    coverSrc: "/images/places/23.jpg",
    rating: 4,
    price: 3991
  },
  {
    id: 9,
    title: "Redhold",
    noodbed: 1,
    bathroom: 1,
    area: 47,
    avaible: false,
    county: "United States",
    address: "1988 Rigney Drive",
    category: "Apartment",
    coverSrc: "/images/places/36.jpg",
    rating: 4,
    price: 4149
  },
  {
    id: 10,
    title: "Konklab",
    noodbed: 4,
    bathroom: 3,
    area: 17,
    avaible: false,
    county: "Australia",
    address: "220 Utah Hill",
    category: "House",
    coverSrc: "/images/places/6.jpg",
    rating: 1,
    price: 2690
  },
  {
    id: 11,
    title: "Redhold",
    noodbed: 4,
    bathroom: 2,
    area: 68,
    avaible: true,
    county: "France",
    address: "078 8th Avenue",
    category: "Hotel",
    coverSrc: "/images/places/31.jpg",
    rating: 3,
    price: 2658
  },
  {
    id: 12,
    title: "Konklab",
    noodbed: 3,
    bathroom: 2,
    area: 24,
    avaible: true,
    county: "India",
    address: "15 Melody Street",
    category: "Hotel",
    coverSrc: "/images/places/6.jpg",
    rating: 1,
    price: 1058
  },
  {
    id: 13,
    title: "Bitwolf",
    noodbed: 4,
    bathroom: 2,
    area: 51,
    avaible: false,
    county: "Japan",
    address: "4961 Dapin Street",
    category: "Cottage",
    coverSrc: "/images/places/41.jpg",
    rating: 3,
    price: 3297
  },
  {
    id: 14,
    title: "Trippledex",
    noodbed: 2,
    bathroom: 1,
    area: 89,
    avaible: true,
    county: "Canada",
    address: "1660 Saint Paul Parkway",
    category: "Apartment",
    coverSrc: "/images/places/2.jpg",
    rating: 5,
    price: 3882
  },
  {
    id: 15,
    title: "Flexidy",
    noodbed: 1,
    bathroom: 1,
    area: 50,
    avaible: true,
    county: "Canada",
    address: "81 Graceland Point",
    category: "House",
    coverSrc: "/images/places/18.jpg",
    rating: 4,
    price: 2191
  },
  {
    id: 16,
    title: "Wrapsafe",
    noodbed: 2,
    bathroom: 3,
    area: 28,
    avaible: true,
    county: "Japan",
    address: "3 Cambridge Trail",
    category: "Farm House",
    coverSrc: "/images/places/12.jpg",
    rating: 4,
    price: 2720
  },
  {
    id: 17,
    title: "Tres-Zap",
    noodbed: 1,
    bathroom: 3,
    area: 87,
    avaible: false,
    county: "United States",
    address: "4365 Green Ridge Center",
    category: "Motel",
    coverSrc: "/images/places/40.jpg",
    rating: 4,
    price: 1826
  },
  {
    id: 18,
    title: "Daltfresh",
    noodbed: 1,
    bathroom: 3,
    area: 67,
    avaible: false,
    county: "India",
    address: "706 Toban Hill",
    category: "Hotel",
    coverSrc: "/images/places/29.jpg",
    rating: 3,
    price: 3657
  },
  {
    id: 19,
    title: "Subin",
    noodbed: 3,
    bathroom: 1,
    area: 13,
    avaible: false,
    county: "Germany",
    address: "74 Dawn Parkway",
    category: "Hotel",
    coverSrc: "/images/places/7.jpg",
    rating: 3,
    price: 3290
  },
  {
    id: 20,
    title: "Regrant",
    noodbed: 2,
    bathroom: 1,
    area: 70,
    avaible: false,
    county: "United States",
    address: "7673 Bunting Place",
    category: "Lounge",
    coverSrc: "/images/places/39.jpg",
    rating: 1,
    price: 2642
  },
  {
    id: 21,
    title: "Otcom",
    noodbed: 2,
    bathroom: 2,
    area: 13,
    avaible: true,
    county: "Japan",
    address: "58 Susan Point",
    category: "Motel",
    coverSrc: "/images/places/22.jpg",
    rating: 4,
    price: 4916
  },
  {
    id: 22,
    title: "Rank",
    noodbed: 4,
    bathroom: 2,
    area: 61,
    avaible: true,
    county: "United States",
    address: "7277 Dakota Plaza",
    category: "Villa",
    coverSrc: "/images/places/15.jpg",
    rating: 3,
    price: 2670
  },
  {
    id: 23,
    title: "Wrapsafe",
    noodbed: 3,
    bathroom: 1,
    area: 54,
    avaible: false,
    county: "Canada",
    address: "39846 Schlimgen Parkway",
    category: "Cottage",
    coverSrc: "/images/places/20.jpg",
    rating: 5,
    price: 4277
  },
  {
    id: 24,
    title: "Flexidy",
    noodbed: 4,
    bathroom: 1,
    area: 35,
    avaible: true,
    county: "Canada",
    address: "2 Londonderry Court",
    category: "Apartment",
    coverSrc: "/images/places/24.jpg",
    rating: 5,
    price: 1455
  },
  {
    id: 25,
    title: "Mat Lam Tam",
    noodbed: 2,
    bathroom: 3,
    area: 57,
    avaible: false,
    county: "Canada",
    address: "50 Bunker Hill Way",
    category: "Villa",
    coverSrc: "/images/places/9.jpg",
    rating: 4,
    price: 1938
  },
  {
    id: 26,
    title: "Kanlam",
    noodbed: 4,
    bathroom: 2,
    area: 84,
    avaible: true,
    county: "United States",
    address: "140 Pankratz Park",
    category: "Lounge",
    coverSrc: "/images/places/18.jpg",
    rating: 1,
    price: 1825
  },
  {
    id: 27,
    title: "Cardify",
    noodbed: 3,
    bathroom: 3,
    area: 72,
    avaible: false,
    county: "France",
    address: "16347 Bonner Lane",
    category: "Villa",
    coverSrc: "/images/places/15.jpg",
    rating: 4,
    price: 3346
  },
  {
    id: 28,
    title: "Fixflex",
    noodbed: 4,
    bathroom: 3,
    area: 99,
    avaible: true,
    county: "India",
    address: "8082 Laurel Hill",
    category: "House",
    coverSrc: "/images/places/11.jpg",
    rating: 3,
    price: 1561
  },
  {
    id: 29,
    title: "Transcof",
    noodbed: 3,
    bathroom: 2,
    area: 44,
    avaible: false,
    county: "Germany",
    address: "61118 Maryland Crossing",
    category: "Motel",
    coverSrc: "/images/places/3.jpg",
    rating: 5,
    price: 3212
  },
  {
    id: 30,
    title: "Bamity",
    noodbed: 3,
    bathroom: 3,
    area: 28,
    avaible: false,
    county: "Canada",
    address: "64066 Oak Drive",
    category: "Hostel",
    coverSrc: "/images/places/36.jpg",
    rating: 1,
    price: 4262
  },
  {
    id: 31,
    title: "Sonair",
    noodbed: 3,
    bathroom: 1,
    area: 48,
    avaible: true,
    county: "Australia",
    address: "14343 Green Alley",
    category: "Villa",
    coverSrc: "/images/places/22.jpg",
    rating: 1,
    price: 1204
  },
  {
    id: 32,
    title: "Alpha",
    noodbed: 3,
    bathroom: 1,
    area: 60,
    avaible: true,
    county: "United States",
    address: "8 Lake View Way",
    category: "Motel",
    coverSrc: "/images/places/11.jpg",
    rating: 2,
    price: 4170
  },
  {
    id: 33,
    title: "Domainer",
    noodbed: 1,
    bathroom: 1,
    area: 93,
    avaible: false,
    county: "Canada",
    address: "18705 Monument Circle",
    category: "Hotel",
    coverSrc: "/images/places/33.jpg",
    rating: 4,
    price: 4123
  },
  {
    id: 34,
    title: "Ventosanzap",
    noodbed: 2,
    bathroom: 3,
    area: 95,
    avaible: false,
    county: "United States",
    address: "871 Tomscot Plaza",
    category: "Motel",
    coverSrc: "/images/places/33.jpg",
    rating: 4,
    price: 2858
  },
  {
    id: 35,
    title: "Zathin",
    noodbed: 1,
    bathroom: 1,
    area: 28,
    avaible: true,
    county: "Australia",
    address: "48410 Florence Junction",
    category: "House",
    coverSrc: "/images/places/3.jpg",
    rating: 2,
    price: 4332
  },
  {
    id: 36,
    title: "Rank",
    noodbed: 4,
    bathroom: 1,
    area: 96,
    avaible: false,
    county: "Japan",
    address: "10175 Mayfield Way",
    category: "Motel",
    coverSrc: "/images/places/8.jpg",
    rating: 2,
    price: 3936
  },
  {
    id: 37,
    title: "Domainer",
    noodbed: 1,
    bathroom: 3,
    area: 91,
    avaible: false,
    county: "Canada",
    address: "91421 Kinsman Junction",
    category: "Motel",
    coverSrc: "/images/places/4.jpg",
    rating: 1,
    price: 2579
  },
  {
    id: 38,
    title: "Temp",
    noodbed: 3,
    bathroom: 3,
    area: 27,
    avaible: false,
    county: "India",
    address: "315 Lighthouse Bay Road",
    category: "House",
    coverSrc: "/images/places/45.jpg",
    rating: 4,
    price: 3655
  },
  {
    id: 39,
    title: "Alpha",
    noodbed: 1,
    bathroom: 1,
    area: 81,
    avaible: false,
    county: "Japan",
    address: "800 Vahlen Pass",
    category: "Farm House",
    coverSrc: "/images/places/19.jpg",
    rating: 2,
    price: 4027
  },
  {
    id: 40,
    title: "Tempsoft",
    noodbed: 4,
    bathroom: 3,
    area: 88,
    avaible: false,
    county: "India",
    address: "2819 Bartelt Center",
    category: "Hostel",
    coverSrc: "/images/places/10.jpg",
    rating: 2,
    price: 4022
  },
  {
    id: 41,
    title: "Keylex",
    noodbed: 2,
    bathroom: 3,
    area: 22,
    avaible: false,
    county: "Germany",
    address: "62 Waxwing Trail",
    category: "Farm House",
    coverSrc: "/images/places/3.jpg",
    rating: 5,
    price: 1322
  },
  {
    id: 42,
    title: "Flowdesk",
    noodbed: 2,
    bathroom: 2,
    area: 79,
    avaible: false,
    county: "Japan",
    address: "04 Brentwood Lane",
    category: "House",
    coverSrc: "/images/places/14.jpg",
    rating: 3,
    price: 1885
  },
  {
    id: 43,
    title: "Flowdesk",
    noodbed: 4,
    bathroom: 3,
    area: 71,
    avaible: false,
    county: "Germany",
    address: "495 Stephen Hill",
    category: "Lounge",
    coverSrc: "/images/places/10.jpg",
    rating: 4,
    price: 1378
  },
  {
    id: 44,
    title: "Namfix",
    noodbed: 2,
    bathroom: 3,
    area: 59,
    avaible: false,
    county: "United States",
    address: "9171 Oak Place",
    category: "Apartment",
    coverSrc: "/images/places/40.jpg",
    rating: 5,
    price: 1455
  },
  {
    id: 45,
    title: "Konklux",
    noodbed: 3,
    bathroom: 3,
    area: 10,
    avaible: true,
    county: "Canada",
    address: "972 Waywood Pass",
    category: "Apartment",
    coverSrc: "/images/places/9.jpg",
    rating: 5,
    price: 4371
  },
  {
    id: 46,
    title: "Home Ing",
    noodbed: 2,
    bathroom: 3,
    area: 23,
    avaible: true,
    county: "United States",
    address: "4387 David Way",
    category: "Lounge",
    coverSrc: "/images/places/10.jpg",
    rating: 3,
    price: 2590
  },
  {
    id: 47,
    title: "Andalax",
    noodbed: 3,
    bathroom: 2,
    area: 72,
    avaible: false,
    county: "Germany",
    address: "609 Ridge Oak Drive",
    category: "Hostel",
    coverSrc: "/images/places/45.jpg",
    rating: 1,
    price: 3436
  },
  {
    id: 48,
    title: "Home Ing",
    noodbed: 4,
    bathroom: 1,
    area: 34,
    avaible: false,
    county: "France",
    address: "8084 Troy Way",
    category: "Hotel",
    coverSrc: "/images/places/9.jpg",
    rating: 4,
    price: 4338
  },
  {
    id: 49,
    title: "Biodex",
    noodbed: 1,
    bathroom: 2,
    area: 6,
    avaible: true,
    county: "Japan",
    address: "1656 Oak Valley Street",
    category: "Hotel",
    coverSrc: "/images/places/10.jpg",
    rating: 3,
    price: 3195
  },
  {
    id: 50,
    title: "Tresom",
    noodbed: 2,
    bathroom: 2,
    area: 98,
    avaible: false,
    county: "Japan",
    address: "122 Lakeland Court",
    category: "Hostel",
    coverSrc: "/images/places/32.jpg",
    rating: 3,
    price: 3361
  },
  {
    id: 51,
    title: "Viva",
    noodbed: 2,
    bathroom: 1,
    area: 42,
    avaible: true,
    county: "Germany",
    address: "9 Hauk Pass",
    category: "Apartment",
    coverSrc: "/images/places/45.jpg",
    rating: 1,
    price: 1558
  },
  {
    id: 52,
    title: "Stronghold",
    noodbed: 1,
    bathroom: 2,
    area: 14,
    avaible: false,
    county: "United States",
    address: "905 Lake View Plaza",
    category: "Villa",
    coverSrc: "/images/places/13.jpg",
    rating: 3,
    price: 3244
  },
  {
    id: 53,
    title: "Aerified",
    noodbed: 4,
    bathroom: 3,
    area: 38,
    avaible: false,
    county: "Japan",
    address: "861 Menomonie Plaza",
    category: "Apartment",
    coverSrc: "/images/places/38.jpg",
    rating: 4,
    price: 4118
  },
  {
    id: 54,
    title: "Pannier",
    noodbed: 3,
    bathroom: 2,
    area: 50,
    avaible: false,
    county: "India",
    address: "0591 Arrowood Drive",
    category: "House",
    coverSrc: "/images/places/43.jpg",
    rating: 2,
    price: 4464
  },
  {
    id: 55,
    title: "Toughjoyfax",
    noodbed: 4,
    bathroom: 2,
    area: 90,
    avaible: true,
    county: "India",
    address: "63654 Norway Maple Crossing",
    category: "Motel",
    coverSrc: "/images/places/6.jpg",
    rating: 5,
    price: 1683
  },
  {
    id: 56,
    title: "Bamity",
    noodbed: 2,
    bathroom: 1,
    area: 55,
    avaible: false,
    county: "India",
    address: "03 Sunnyside Plaza",
    category: "Villa",
    coverSrc: "/images/places/34.jpg",
    rating: 2,
    price: 3461
  },
  {
    id: 57,
    title: "Transcof",
    noodbed: 2,
    bathroom: 2,
    area: 12,
    avaible: false,
    county: "France",
    address: "3 Kim Place",
    category: "Apartment",
    coverSrc: "/images/places/11.jpg",
    rating: 3,
    price: 2775
  },
  {
    id: 58,
    title: "Quo Lux",
    noodbed: 3,
    bathroom: 2,
    area: 38,
    avaible: true,
    county: "India",
    address: "9 Crowley Drive",
    category: "Apartment",
    coverSrc: "/images/places/44.jpg",
    rating: 1,
    price: 2070
  },
  {
    id: 59,
    title: "Stim",
    noodbed: 4,
    bathroom: 1,
    area: 7,
    avaible: true,
    county: "United States",
    address: "20 Blue Bill Park Drive",
    category: "Motel",
    coverSrc: "/images/places/17.jpg",
    rating: 1,
    price: 1342
  },
  {
    id: 60,
    title: "Zamit",
    noodbed: 3,
    bathroom: 2,
    area: 63,
    avaible: true,
    county: "Japan",
    address: "37330 Harbort Point",
    category: "Hostel",
    coverSrc: "/images/places/45.jpg",
    rating: 3,
    price: 3330
  },
  {
    id: 61,
    title: "Cookley",
    noodbed: 3,
    bathroom: 2,
    area: 28,
    avaible: true,
    county: "India",
    address: "7036 Boyd Terrace",
    category: "Apartment",
    coverSrc: "/images/places/37.jpg",
    rating: 2,
    price: 4478
  },
  {
    id: 62,
    title: "Lotlux",
    noodbed: 4,
    bathroom: 1,
    area: 32,
    avaible: true,
    county: "Japan",
    address: "54702 School Park",
    category: "Hotel",
    coverSrc: "/images/places/3.jpg",
    rating: 3,
    price: 1638
  },
  {
    id: 63,
    title: "Kanlam",
    noodbed: 3,
    bathroom: 2,
    area: 75,
    avaible: true,
    county: "India",
    address: "094 Rowland Alley",
    category: "Farm House",
    coverSrc: "/images/places/44.jpg",
    rating: 3,
    price: 3959
  },
  {
    id: 64,
    title: "Alphazap",
    noodbed: 4,
    bathroom: 3,
    area: 88,
    avaible: true,
    county: "Germany",
    address: "77595 Mcguire Trail",
    category: "Cottage",
    coverSrc: "/images/places/46.jpg",
    rating: 2,
    price: 4799
  },
  {
    id: 65,
    title: "Zoolab",
    noodbed: 2,
    bathroom: 2,
    area: 45,
    avaible: true,
    county: "India",
    address: "11732 Florence Crossing",
    category: "Motel",
    coverSrc: "/images/places/9.jpg",
    rating: 1,
    price: 1293
  },
  {
    id: 66,
    title: "Tresom",
    noodbed: 1,
    bathroom: 2,
    area: 61,
    avaible: true,
    county: "United States",
    address: "9 Bluestem Trail",
    category: "Motel",
    coverSrc: "/images/places/2.jpg",
    rating: 4,
    price: 4979
  },
  {
    id: 67,
    title: "Regrant",
    noodbed: 1,
    bathroom: 1,
    area: 89,
    avaible: true,
    county: "Canada",
    address: "342 Straubel Trail",
    category: "Apartment",
    coverSrc: "/images/places/12.jpg",
    rating: 3,
    price: 2859
  },
  {
    id: 68,
    title: "Mat Lam Tam",
    noodbed: 2,
    bathroom: 2,
    area: 81,
    avaible: false,
    county: "Germany",
    address: "035 Clarendon Drive",
    category: "House",
    coverSrc: "/images/places/37.jpg",
    rating: 3,
    price: 1736
  },
  {
    id: 69,
    title: "Kanlam",
    noodbed: 2,
    bathroom: 1,
    area: 45,
    avaible: false,
    county: "United States",
    address: "1 Scott Avenue",
    category: "Lounge",
    coverSrc: "/images/places/12.jpg",
    rating: 4,
    price: 2129
  },
  {
    id: 70,
    title: "Lotstring",
    noodbed: 4,
    bathroom: 2,
    area: 70,
    avaible: false,
    county: "Japan",
    address: "9 Crownhardt Street",
    category: "Villa",
    coverSrc: "/images/places/7.jpg",
    rating: 1,
    price: 3736
  },
  {
    id: 71,
    title: "Asoka",
    noodbed: 4,
    bathroom: 1,
    area: 31,
    avaible: true,
    county: "India",
    address: "815 Crownhardt Crossing",
    category: "Lounge",
    coverSrc: "/images/places/27.jpg",
    rating: 2,
    price: 4782
  },
  {
    id: 72,
    title: "Lotlux",
    noodbed: 3,
    bathroom: 2,
    area: 60,
    avaible: false,
    county: "Germany",
    address: "99855 Reinke Circle",
    category: "Cottage",
    coverSrc: "/images/places/14.jpg",
    rating: 3,
    price: 4709
  },
  {
    id: 73,
    title: "Aerified",
    noodbed: 4,
    bathroom: 3,
    area: 63,
    avaible: true,
    county: "Australia",
    address: "2 Buhler Avenue",
    category: "House",
    coverSrc: "/images/places/16.jpg",
    rating: 4,
    price: 3835
  },
  {
    id: 74,
    title: "Hatity",
    noodbed: 3,
    bathroom: 2,
    area: 79,
    avaible: true,
    county: "Germany",
    address: "50427 Hoffman Hill",
    category: "Motel",
    coverSrc: "/images/places/39.jpg",
    rating: 5,
    price: 4812
  },
  {
    id: 75,
    title: "Voltsillam",
    noodbed: 1,
    bathroom: 1,
    area: 25,
    avaible: true,
    county: "Germany",
    address: "9 Johnson Hill",
    category: "Hotel",
    coverSrc: "/images/places/9.jpg",
    rating: 1,
    price: 1140
  },
  {
    id: 76,
    title: "Opela",
    noodbed: 1,
    bathroom: 2,
    area: 62,
    avaible: true,
    county: "France",
    address: "4 5th Lane",
    category: "Apartment",
    coverSrc: "/images/places/18.jpg",
    rating: 3,
    price: 4322
  },
  {
    id: 77,
    title: "Bitwolf",
    noodbed: 2,
    bathroom: 2,
    area: 81,
    avaible: false,
    county: "India",
    address: "1987 Scoville Trail",
    category: "Motel",
    coverSrc: "/images/places/35.jpg",
    rating: 2,
    price: 4382
  },
  {
    id: 78,
    title: "Bigtax",
    noodbed: 2,
    bathroom: 1,
    area: 11,
    avaible: false,
    county: "United States",
    address: "45 Kim Center",
    category: "Apartment",
    coverSrc: "/images/places/1.jpg",
    rating: 2,
    price: 4289
  },
  {
    id: 79,
    title: "Flowdesk",
    noodbed: 4,
    bathroom: 3,
    area: 1,
    avaible: false,
    county: "France",
    address: "7 Meadow Valley Road",
    category: "Hotel",
    coverSrc: "/images/places/18.jpg",
    rating: 3,
    price: 4772
  },
  {
    id: 80,
    title: "Temp",
    noodbed: 1,
    bathroom: 3,
    area: 19,
    avaible: false,
    county: "United States",
    address: "55 Starling Park",
    category: "Hotel",
    coverSrc: "/images/places/19.jpg",
    rating: 4,
    price: 1962
  },
  {
    id: 81,
    title: "Regrant",
    noodbed: 1,
    bathroom: 3,
    area: 2,
    avaible: true,
    county: "France",
    address: "9828 Maple Wood Place",
    category: "Farm House",
    coverSrc: "/images/places/1.jpg",
    rating: 5,
    price: 1455
  },
  {
    id: 82,
    title: "Mat Lam Tam",
    noodbed: 2,
    bathroom: 3,
    area: 5,
    avaible: false,
    county: "France",
    address: "3 Prairie Rose Junction",
    category: "Apartment",
    coverSrc: "/images/places/38.jpg",
    rating: 4,
    price: 4050
  },
  {
    id: 83,
    title: "Stronghold",
    noodbed: 4,
    bathroom: 1,
    area: 70,
    avaible: true,
    county: "United States",
    address: "02109 Myrtle Avenue",
    category: "Hostel",
    coverSrc: "/images/places/13.jpg",
    rating: 1,
    price: 3649
  },
  {
    id: 84,
    title: "Cookley",
    noodbed: 1,
    bathroom: 2,
    area: 77,
    avaible: true,
    county: "Japan",
    address: "2 Norway Maple Alley",
    category: "Villa",
    coverSrc: "/images/places/22.jpg",
    rating: 2,
    price: 1408
  },
  {
    id: 85,
    title: "Mat Lam Tam",
    noodbed: 2,
    bathroom: 3,
    area: 62,
    avaible: false,
    county: "Japan",
    address: "729 Sugar Parkway",
    category: "Hotel",
    coverSrc: "/images/places/17.jpg",
    rating: 3,
    price: 3177
  },
  {
    id: 86,
    title: "It",
    noodbed: 4,
    bathroom: 1,
    area: 43,
    avaible: true,
    county: "Canada",
    address: "7 Fremont Lane",
    category: "Villa",
    coverSrc: "/images/places/17.jpg",
    rating: 1,
    price: 2172
  },
  {
    id: 87,
    title: "Cardguard",
    noodbed: 3,
    bathroom: 3,
    area: 10,
    avaible: false,
    county: "Australia",
    address: "94708 Kenwood Lane",
    category: "Cottage",
    coverSrc: "/images/places/30.jpg",
    rating: 2,
    price: 2130
  },
  {
    id: 88,
    title: "Voltsillam",
    noodbed: 4,
    bathroom: 3,
    area: 48,
    avaible: false,
    county: "India",
    address: "91805 Huxley Street",
    category: "House",
    coverSrc: "/images/places/24.jpg",
    rating: 1,
    price: 2736
  },
  {
    id: 89,
    title: "Redhold",
    noodbed: 2,
    bathroom: 3,
    area: 40,
    avaible: true,
    county: "India",
    address: "647 Laurel Place",
    category: "Cottage",
    coverSrc: "/images/places/19.jpg",
    rating: 2,
    price: 3005
  },
  {
    id: 90,
    title: "Zontrax",
    noodbed: 3,
    bathroom: 3,
    area: 50,
    avaible: true,
    county: "Japan",
    address: "463 Bellgrove Crossing",
    category: "House",
    coverSrc: "/images/places/15.jpg",
    rating: 4,
    price: 2133
  },
  {
    id: 91,
    title: "Kanlam",
    noodbed: 4,
    bathroom: 1,
    area: 70,
    avaible: false,
    county: "Japan",
    address: "8 Coleman Crossing",
    category: "Hostel",
    coverSrc: "/images/places/25.jpg",
    rating: 2,
    price: 3332
  },
  {
    id: 92,
    title: "Flexidy",
    noodbed: 3,
    bathroom: 3,
    area: 85,
    avaible: true,
    county: "India",
    address: "5 Farwell Crossing",
    category: "Lounge",
    coverSrc: "/images/places/27.jpg",
    rating: 3,
    price: 2774
  },
  {
    id: 93,
    title: "Veribet",
    noodbed: 4,
    bathroom: 3,
    area: 53,
    avaible: false,
    county: "India",
    address: "9 Ilene Place",
    category: "Apartment",
    coverSrc: "/images/places/17.jpg",
    rating: 3,
    price: 1001
  },
  {
    id: 94,
    title: "Tresom",
    noodbed: 1,
    bathroom: 1,
    area: 19,
    avaible: true,
    county: "Australia",
    address: "32 Shoshone Trail",
    category: "Apartment",
    coverSrc: "/images/places/36.jpg",
    rating: 5,
    price: 2822
  },
  {
    id: 95,
    title: "Bitwolf",
    noodbed: 3,
    bathroom: 3,
    area: 50,
    avaible: true,
    county: "United States",
    address: "4984 Dennis Pass",
    category: "Hostel",
    coverSrc: "/images/places/45.jpg",
    rating: 2,
    price: 2084
  },
  {
    id: 96,
    title: "Wrapsafe",
    noodbed: 1,
    bathroom: 3,
    area: 27,
    avaible: true,
    county: "France",
    address: "633 Veith Drive",
    category: "Villa",
    coverSrc: "/images/places/32.jpg",
    rating: 4,
    price: 2380
  },
  {
    id: 97,
    title: "Konklux",
    noodbed: 1,
    bathroom: 2,
    area: 83,
    avaible: false,
    county: "Japan",
    address: "86988 Crowley Avenue",
    category: "Farm House",
    coverSrc: "/images/places/39.jpg",
    rating: 3,
    price: 4346
  },
  {
    id: 98,
    title: "Zoolab",
    noodbed: 3,
    bathroom: 1,
    area: 78,
    avaible: true,
    county: "United States",
    address: "517 Rigney Court",
    category: "Apartment",
    coverSrc: "/images/places/34.jpg",
    rating: 4,
    price: 3153
  },
  {
    id: 99,
    title: "Stringtough",
    noodbed: 3,
    bathroom: 2,
    area: 8,
    avaible: false,
    county: "Australia",
    address: "3 Sage Trail",
    category: "Farm House",
    coverSrc: "/images/places/46.jpg",
    rating: 2,
    price: 3249
  },
  {
    id: 100,
    title: "Cookley",
    noodbed: 4,
    bathroom: 2,
    area: 22,
    avaible: true,
    county: "Canada",
    address: "5 Barby Center",
    category: "Lounge",
    coverSrc: "/images/places/18.jpg",
    rating: 3,
    price: 1188
  },
  {
    id: 101,
    title: "Stronghold",
    noodbed: 4,
    bathroom: 1,
    area: 62,
    avaible: false,
    county: "Australia",
    address: "0 Eastlawn Street",
    category: "Hotel",
    coverSrc: "/images/places/22.jpg",
    rating: 1,
    price: 3387
  },
  {
    id: 102,
    title: "Wrapsafe",
    noodbed: 1,
    bathroom: 3,
    area: 55,
    avaible: false,
    county: "India",
    address: "122 Hovde Alley",
    category: "House",
    coverSrc: "/images/places/35.jpg",
    rating: 3,
    price: 4082
  },
  {
    id: 103,
    title: "Latlux",
    noodbed: 4,
    bathroom: 2,
    area: 83,
    avaible: true,
    county: "Australia",
    address: "59412 7th Street",
    category: "Apartment",
    coverSrc: "/images/places/2.jpg",
    rating: 5,
    price: 2235
  },
  {
    id: 104,
    title: "Regrant",
    noodbed: 2,
    bathroom: 3,
    area: 95,
    avaible: true,
    county: "Japan",
    address: "17 Sage Lane",
    category: "Motel",
    coverSrc: "/images/places/30.jpg",
    rating: 1,
    price: 4370
  },
  {
    id: 105,
    title: "Konklux",
    noodbed: 3,
    bathroom: 1,
    area: 63,
    avaible: false,
    county: "Germany",
    address: "0 Moland Drive",
    category: "Farm House",
    coverSrc: "/images/places/21.jpg",
    rating: 2,
    price: 3033
  },
  {
    id: 106,
    title: "Namfix",
    noodbed: 1,
    bathroom: 2,
    area: 66,
    avaible: true,
    county: "Germany",
    address: "8149 Marcy Junction",
    category: "Cottage",
    coverSrc: "/images/places/5.jpg",
    rating: 3,
    price: 4379
  },
  {
    id: 107,
    title: "Tin",
    noodbed: 1,
    bathroom: 1,
    area: 13,
    avaible: true,
    county: "India",
    address: "62038 Oriole Place",
    category: "Motel",
    coverSrc: "/images/places/24.jpg",
    rating: 3,
    price: 4900
  },
  {
    id: 108,
    title: "Toughjoyfax",
    noodbed: 2,
    bathroom: 2,
    area: 59,
    avaible: true,
    county: "Canada",
    address: "720 Lakeland Place",
    category: "Hostel",
    coverSrc: "/images/places/27.jpg",
    rating: 5,
    price: 1512
  },
  {
    id: 109,
    title: "Fixflex",
    noodbed: 1,
    bathroom: 1,
    area: 58,
    avaible: false,
    county: "France",
    address: "89 Atwood Terrace",
    category: "Motel",
    coverSrc: "/images/places/3.jpg",
    rating: 3,
    price: 4616
  },
  {
    id: 110,
    title: "Fintone",
    noodbed: 4,
    bathroom: 3,
    area: 45,
    avaible: true,
    county: "Japan",
    address: "3 Claremont Street",
    category: "Cottage",
    coverSrc: "/images/places/29.jpg",
    rating: 3,
    price: 3014
  },
  {
    id: 111,
    title: "Kanlam",
    noodbed: 4,
    bathroom: 3,
    area: 1,
    avaible: false,
    county: "Germany",
    address: "16134 Melrose Crossing",
    category: "Motel",
    coverSrc: "/images/places/42.jpg",
    rating: 4,
    price: 2257
  },
  {
    id: 112,
    title: "Tempsoft",
    noodbed: 4,
    bathroom: 3,
    area: 57,
    avaible: true,
    county: "Canada",
    address: "69 Old Shore Crossing",
    category: "Cottage",
    coverSrc: "/images/places/44.jpg",
    rating: 2,
    price: 4021
  },
  {
    id: 113,
    title: "Veribet",
    noodbed: 3,
    bathroom: 1,
    area: 26,
    avaible: false,
    county: "France",
    address: "1 Northport Lane",
    category: "Motel",
    coverSrc: "/images/places/43.jpg",
    rating: 5,
    price: 3366
  },
  {
    id: 114,
    title: "Stringtough",
    noodbed: 4,
    bathroom: 3,
    area: 25,
    avaible: false,
    county: "Canada",
    address: "6047 Becker Point",
    category: "Apartment",
    coverSrc: "/images/places/10.jpg",
    rating: 2,
    price: 2796
  },
  {
    id: 115,
    title: "Zoolab",
    noodbed: 3,
    bathroom: 2,
    area: 27,
    avaible: true,
    county: "Germany",
    address: "94 Arizona Parkway",
    category: "Villa",
    coverSrc: "/images/places/15.jpg",
    rating: 4,
    price: 4431
  },
  {
    id: 116,
    title: "Hatity",
    noodbed: 2,
    bathroom: 3,
    area: 16,
    avaible: true,
    county: "Canada",
    address: "1 Claremont Hill",
    category: "House",
    coverSrc: "/images/places/30.jpg",
    rating: 4,
    price: 3574
  },
  {
    id: 117,
    title: "Latlux",
    noodbed: 4,
    bathroom: 1,
    area: 83,
    avaible: true,
    county: "United States",
    address: "475 Vernon Center",
    category: "Farm House",
    coverSrc: "/images/places/6.jpg",
    rating: 4,
    price: 4342
  },
  {
    id: 118,
    title: "Biodex",
    noodbed: 2,
    bathroom: 2,
    area: 30,
    avaible: false,
    county: "Japan",
    address: "9 School Hill",
    category: "Hostel",
    coverSrc: "/images/places/14.jpg",
    rating: 5,
    price: 3783
  },
  {
    id: 119,
    title: "Tin",
    noodbed: 3,
    bathroom: 3,
    area: 53,
    avaible: true,
    county: "India",
    address: "275 Knutson Pass",
    category: "House",
    coverSrc: "/images/places/41.jpg",
    rating: 4,
    price: 1829
  },
  {
    id: 120,
    title: "Bamity",
    noodbed: 2,
    bathroom: 3,
    area: 93,
    avaible: false,
    county: "India",
    address: "24422 Buhler Road",
    category: "Lounge",
    coverSrc: "/images/places/44.jpg",
    rating: 4,
    price: 4378
  },
  {
    id: 121,
    title: "Cardify",
    noodbed: 4,
    bathroom: 2,
    area: 16,
    avaible: true,
    county: "France",
    address: "8 Ryan Lane",
    category: "Cottage",
    coverSrc: "/images/places/46.jpg",
    rating: 4,
    price: 4609
  },
  {
    id: 122,
    title: "Zamit",
    noodbed: 1,
    bathroom: 3,
    area: 98,
    avaible: false,
    county: "France",
    address: "5 Manufacturers Point",
    category: "Hostel",
    coverSrc: "/images/places/34.jpg",
    rating: 1,
    price: 4759
  },
  {
    id: 123,
    title: "Y-Solowarm",
    noodbed: 4,
    bathroom: 3,
    area: 29,
    avaible: false,
    county: "Japan",
    address: "7323 Lien Alley",
    category: "Apartment",
    coverSrc: "/images/places/30.jpg",
    rating: 5,
    price: 4270
  },
  {
    id: 124,
    title: "Greenlam",
    noodbed: 2,
    bathroom: 3,
    area: 91,
    avaible: true,
    county: "India",
    address: "44 Heffernan Trail",
    category: "Hostel",
    coverSrc: "/images/places/21.jpg",
    rating: 5,
    price: 4632
  },
  {
    id: 125,
    title: "Toughjoyfax",
    noodbed: 2,
    bathroom: 2,
    area: 88,
    avaible: true,
    county: "Canada",
    address: "08 Reinke Place",
    category: "Farm House",
    coverSrc: "/images/places/32.jpg",
    rating: 1,
    price: 2484
  },
  {
    id: 126,
    title: "Job",
    noodbed: 4,
    bathroom: 2,
    area: 46,
    avaible: false,
    county: "Canada",
    address: "63376 Merchant Terrace",
    category: "Cottage",
    coverSrc: "/images/places/26.jpg",
    rating: 2,
    price: 4715
  },
  {
    id: 127,
    title: "Transcof",
    noodbed: 2,
    bathroom: 3,
    area: 30,
    avaible: true,
    county: "Japan",
    address: "62 Ohio Court",
    category: "Hotel",
    coverSrc: "/images/places/32.jpg",
    rating: 5,
    price: 3989
  },
  {
    id: 128,
    title: "Home Ing",
    noodbed: 1,
    bathroom: 2,
    area: 16,
    avaible: true,
    county: "United States",
    address: "3 Sugar Crossing",
    category: "Hotel",
    coverSrc: "/images/places/38.jpg",
    rating: 1,
    price: 2164
  },
  {
    id: 129,
    title: "Holdlamis",
    noodbed: 2,
    bathroom: 3,
    area: 57,
    avaible: true,
    county: "India",
    address: "2 Monterey Circle",
    category: "House",
    coverSrc: "/images/places/37.jpg",
    rating: 2,
    price: 4587
  },
  {
    id: 130,
    title: "Domainer",
    noodbed: 4,
    bathroom: 1,
    area: 20,
    avaible: false,
    county: "United States",
    address: "07 Dixon Circle",
    category: "Motel",
    coverSrc: "/images/places/24.jpg",
    rating: 5,
    price: 1474
  },
  {
    id: 131,
    title: "Bigtax",
    noodbed: 4,
    bathroom: 3,
    area: 72,
    avaible: true,
    county: "India",
    address: "7 Corscot Alley",
    category: "Hostel",
    coverSrc: "/images/places/42.jpg",
    rating: 2,
    price: 1891
  },
  {
    id: 132,
    title: "Zoolab",
    noodbed: 4,
    bathroom: 2,
    area: 82,
    avaible: true,
    county: "United States",
    address: "64 Knutson Park",
    category: "Hotel",
    coverSrc: "/images/places/26.jpg",
    rating: 2,
    price: 3597
  },
  {
    id: 133,
    title: "Tin",
    noodbed: 1,
    bathroom: 3,
    area: 32,
    avaible: true,
    county: "Australia",
    address: "7512 Kennedy Court",
    category: "Apartment",
    coverSrc: "/images/places/41.jpg",
    rating: 1,
    price: 1782
  },
  {
    id: 134,
    title: "Fintone",
    noodbed: 1,
    bathroom: 2,
    area: 44,
    avaible: true,
    county: "Canada",
    address: "7633 Menomonie Hill",
    category: "Motel",
    coverSrc: "/images/places/17.jpg",
    rating: 2,
    price: 3034
  },
  {
    id: 135,
    title: "Sub-Ex",
    noodbed: 3,
    bathroom: 3,
    area: 32,
    avaible: true,
    county: "France",
    address: "5043 American Ash Road",
    category: "Farm House",
    coverSrc: "/images/places/35.jpg",
    rating: 5,
    price: 2815
  },
  {
    id: 136,
    title: "Cardguard",
    noodbed: 2,
    bathroom: 2,
    area: 89,
    avaible: false,
    county: "United States",
    address: "1 Redwing Avenue",
    category: "Hotel",
    coverSrc: "/images/places/5.jpg",
    rating: 5,
    price: 1806
  },
  {
    id: 137,
    title: "Ronstring",
    noodbed: 4,
    bathroom: 1,
    area: 24,
    avaible: false,
    county: "Canada",
    address: "44 Washington Court",
    category: "Hostel",
    coverSrc: "/images/places/7.jpg",
    rating: 5,
    price: 1966
  },
  {
    id: 138,
    title: "Tres-Zap",
    noodbed: 1,
    bathroom: 3,
    area: 25,
    avaible: true,
    county: "Canada",
    address: "1588 Superior Court",
    category: "Motel",
    coverSrc: "/images/places/25.jpg",
    rating: 3,
    price: 3183
  },
  {
    id: 139,
    title: "Alpha",
    noodbed: 2,
    bathroom: 3,
    area: 47,
    avaible: false,
    county: "Canada",
    address: "7 Maywood Road",
    category: "Hotel",
    coverSrc: "/images/places/23.jpg",
    rating: 4,
    price: 2179
  },
  {
    id: 140,
    title: "Namfix",
    noodbed: 1,
    bathroom: 3,
    area: 45,
    avaible: false,
    county: "India",
    address: "54837 Westend Court",
    category: "Motel",
    coverSrc: "/images/places/16.jpg",
    rating: 1,
    price: 3547
  },
  {
    id: 141,
    title: "Cardguard",
    noodbed: 4,
    bathroom: 3,
    area: 46,
    avaible: true,
    county: "Canada",
    address: "4402 Twin Pines Park",
    category: "Hotel",
    coverSrc: "/images/places/8.jpg",
    rating: 3,
    price: 1249
  },
  {
    id: 142,
    title: "Y-find",
    noodbed: 2,
    bathroom: 2,
    area: 74,
    avaible: true,
    county: "United States",
    address: "6 Becker Alley",
    category: "Apartment",
    coverSrc: "/images/places/9.jpg",
    rating: 3,
    price: 1918
  },
  {
    id: 143,
    title: "Zamit",
    noodbed: 3,
    bathroom: 1,
    area: 35,
    avaible: false,
    county: "Canada",
    address: "6 1st Crossing",
    category: "Farm House",
    coverSrc: "/images/places/41.jpg",
    rating: 3,
    price: 3242
  },
  {
    id: 144,
    title: "Aerified",
    noodbed: 4,
    bathroom: 3,
    area: 19,
    avaible: true,
    county: "Australia",
    address: "5594 Graceland Circle",
    category: "House",
    coverSrc: "/images/places/32.jpg",
    rating: 4,
    price: 3827
  },
  {
    id: 145,
    title: "Cardify",
    noodbed: 4,
    bathroom: 2,
    area: 99,
    avaible: false,
    county: "India",
    address: "4245 Norway Maple Court",
    category: "Motel",
    coverSrc: "/images/places/31.jpg",
    rating: 3,
    price: 1224
  },
  {
    id: 146,
    title: "Tempsoft",
    noodbed: 2,
    bathroom: 1,
    area: 95,
    avaible: true,
    county: "Japan",
    address: "530 Waywood Junction",
    category: "Cottage",
    coverSrc: "/images/places/23.jpg",
    rating: 1,
    price: 3439
  },
  {
    id: 147,
    title: "Hatity",
    noodbed: 4,
    bathroom: 2,
    area: 97,
    avaible: true,
    county: "Australia",
    address: "70 Hanover Terrace",
    category: "House",
    coverSrc: "/images/places/18.jpg",
    rating: 2,
    price: 3555
  },
  {
    id: 148,
    title: "Bamity",
    noodbed: 1,
    bathroom: 1,
    area: 62,
    avaible: false,
    county: "Japan",
    address: "46 Reinke Point",
    category: "Motel",
    coverSrc: "/images/places/18.jpg",
    rating: 4,
    price: 3287
  },
  {
    id: 149,
    title: "Lotlux",
    noodbed: 1,
    bathroom: 1,
    area: 98,
    avaible: true,
    county: "Canada",
    address: "98588 Sommers Circle",
    category: "Hostel",
    coverSrc: "/images/places/33.jpg",
    rating: 5,
    price: 1930
  },
  {
    id: 150,
    title: "Andalax",
    noodbed: 1,
    bathroom: 2,
    area: 62,
    avaible: true,
    county: "Germany",
    address: "686 Sundown Place",
    category: "Lounge",
    coverSrc: "/images/places/13.jpg",
    rating: 2,
    price: 3269
  },
  {
    id: 151,
    title: "Flexidy",
    noodbed: 3,
    bathroom: 2,
    area: 35,
    avaible: true,
    county: "Australia",
    address: "99556 Eastwood Hill",
    category: "Hostel",
    coverSrc: "/images/places/7.jpg",
    rating: 5,
    price: 3928
  },
  {
    id: 152,
    title: "Sonsing",
    noodbed: 2,
    bathroom: 3,
    area: 53,
    avaible: true,
    county: "Germany",
    address: "14 Orin Terrace",
    category: "House",
    coverSrc: "/images/places/9.jpg",
    rating: 5,
    price: 2304
  },
  {
    id: 153,
    title: "Tres-Zap",
    noodbed: 4,
    bathroom: 3,
    area: 73,
    avaible: false,
    county: "India",
    address: "47 Ludington Lane",
    category: "Farm House",
    coverSrc: "/images/places/30.jpg",
    rating: 1,
    price: 3073
  },
  {
    id: 154,
    title: "Sonair",
    noodbed: 3,
    bathroom: 2,
    area: 3,
    avaible: true,
    county: "Germany",
    address: "79341 Mendota Crossing",
    category: "Cottage",
    coverSrc: "/images/places/40.jpg",
    rating: 4,
    price: 3920
  },
  {
    id: 155,
    title: "Tresom",
    noodbed: 1,
    bathroom: 2,
    area: 87,
    avaible: false,
    county: "India",
    address: "06 Dahle Pass",
    category: "Hotel",
    coverSrc: "/images/places/28.jpg",
    rating: 4,
    price: 3320
  },
  {
    id: 156,
    title: "Solarbreeze",
    noodbed: 2,
    bathroom: 1,
    area: 18,
    avaible: false,
    county: "Australia",
    address: "41 Bartelt Court",
    category: "Villa",
    coverSrc: "/images/places/32.jpg",
    rating: 1,
    price: 4234
  },
  {
    id: 157,
    title: "Toughjoyfax",
    noodbed: 2,
    bathroom: 2,
    area: 8,
    avaible: false,
    county: "France",
    address: "4764 Evergreen Circle",
    category: "Hostel",
    coverSrc: "/images/places/19.jpg",
    rating: 5,
    price: 2354
  },
  {
    id: 158,
    title: "Temp",
    noodbed: 1,
    bathroom: 2,
    area: 70,
    avaible: false,
    county: "Canada",
    address: "017 Rockefeller Pass",
    category: "Hostel",
    coverSrc: "/images/places/36.jpg",
    rating: 2,
    price: 3718
  },
  {
    id: 159,
    title: "Voyatouch",
    noodbed: 3,
    bathroom: 2,
    area: 89,
    avaible: true,
    county: "Australia",
    address: "4 Muir Parkway",
    category: "Hostel",
    coverSrc: "/images/places/30.jpg",
    rating: 3,
    price: 2533
  },
  {
    id: 160,
    title: "Tempsoft",
    noodbed: 2,
    bathroom: 1,
    area: 17,
    avaible: true,
    county: "Australia",
    address: "21 Stuart Park",
    category: "Apartment",
    coverSrc: "/images/places/6.jpg",
    rating: 3,
    price: 4608
  },
  {
    id: 161,
    title: "Ventosanzap",
    noodbed: 2,
    bathroom: 3,
    area: 37,
    avaible: true,
    county: "France",
    address: "76812 Debs Junction",
    category: "Farm House",
    coverSrc: "/images/places/40.jpg",
    rating: 2,
    price: 2067
  },
  {
    id: 162,
    title: "Matsoft",
    noodbed: 3,
    bathroom: 1,
    area: 46,
    avaible: false,
    county: "Australia",
    address: "64742 Alpine Crossing",
    category: "Lounge",
    coverSrc: "/images/places/16.jpg",
    rating: 4,
    price: 3659
  },
  {
    id: 163,
    title: "It",
    noodbed: 1,
    bathroom: 1,
    area: 69,
    avaible: true,
    county: "Australia",
    address: "26192 8th Way",
    category: "Cottage",
    coverSrc: "/images/places/15.jpg",
    rating: 1,
    price: 2060
  },
  {
    id: 164,
    title: "Tresom",
    noodbed: 1,
    bathroom: 3,
    area: 100,
    avaible: true,
    county: "Japan",
    address: "40 Morrow Road",
    category: "Farm House",
    coverSrc: "/images/places/19.jpg",
    rating: 4,
    price: 4154
  },
  {
    id: 165,
    title: "Greenlam",
    noodbed: 3,
    bathroom: 1,
    area: 23,
    avaible: true,
    county: "France",
    address: "139 Anniversary Court",
    category: "Cottage",
    coverSrc: "/images/places/35.jpg",
    rating: 2,
    price: 1140
  },
  {
    id: 166,
    title: "Bigtax",
    noodbed: 1,
    bathroom: 3,
    area: 28,
    avaible: true,
    county: "Japan",
    address: "7148 Annamark Way",
    category: "Motel",
    coverSrc: "/images/places/9.jpg",
    rating: 5,
    price: 3381
  },
  {
    id: 167,
    title: "Daltfresh",
    noodbed: 1,
    bathroom: 1,
    area: 72,
    avaible: false,
    county: "Japan",
    address: "33111 Birchwood Junction",
    category: "House",
    coverSrc: "/images/places/4.jpg",
    rating: 3,
    price: 1765
  },
  {
    id: 168,
    title: "Prodder",
    noodbed: 3,
    bathroom: 3,
    area: 27,
    avaible: true,
    county: "Germany",
    address: "0 Old Gate Terrace",
    category: "Lounge",
    coverSrc: "/images/places/46.jpg",
    rating: 1,
    price: 4089
  },
  {
    id: 169,
    title: "Bitwolf",
    noodbed: 3,
    bathroom: 2,
    area: 67,
    avaible: true,
    county: "India",
    address: "6079 Kropf Junction",
    category: "Lounge",
    coverSrc: "/images/places/11.jpg",
    rating: 4,
    price: 1055
  },
  {
    id: 170,
    title: "Stronghold",
    noodbed: 1,
    bathroom: 3,
    area: 83,
    avaible: true,
    county: "Japan",
    address: "86 Buhler Junction",
    category: "Cottage",
    coverSrc: "/images/places/8.jpg",
    rating: 2,
    price: 2049
  },
  {
    id: 171,
    title: "Ventosanzap",
    noodbed: 4,
    bathroom: 3,
    area: 27,
    avaible: false,
    county: "France",
    address: "801 Rowland Hill",
    category: "House",
    coverSrc: "/images/places/5.jpg",
    rating: 5,
    price: 3736
  },
  {
    id: 172,
    title: "Latlux",
    noodbed: 2,
    bathroom: 3,
    area: 95,
    avaible: true,
    county: "France",
    address: "6482 Hudson Crossing",
    category: "Lounge",
    coverSrc: "/images/places/42.jpg",
    rating: 5,
    price: 2056
  },
  {
    id: 173,
    title: "Treeflex",
    noodbed: 2,
    bathroom: 3,
    area: 14,
    avaible: true,
    county: "Australia",
    address: "53 Golf View Lane",
    category: "Lounge",
    coverSrc: "/images/places/32.jpg",
    rating: 2,
    price: 2965
  },
  {
    id: 174,
    title: "Zamit",
    noodbed: 3,
    bathroom: 2,
    area: 58,
    avaible: true,
    county: "Japan",
    address: "02 Springview Terrace",
    category: "Apartment",
    coverSrc: "/images/places/20.jpg",
    rating: 4,
    price: 4093
  },
  {
    id: 175,
    title: "Subin",
    noodbed: 4,
    bathroom: 1,
    area: 68,
    avaible: true,
    county: "India",
    address: "03704 Fairview Plaza",
    category: "Hostel",
    coverSrc: "/images/places/43.jpg",
    rating: 3,
    price: 4179
  },
  {
    id: 176,
    title: "Hatity",
    noodbed: 1,
    bathroom: 1,
    area: 35,
    avaible: true,
    county: "France",
    address: "8 Bunker Hill Point",
    category: "Lounge",
    coverSrc: "/images/places/5.jpg",
    rating: 5,
    price: 3074
  },
  {
    id: 177,
    title: "Bytecard",
    noodbed: 3,
    bathroom: 1,
    area: 95,
    avaible: false,
    county: "France",
    address: "443 Londonderry Way",
    category: "Apartment",
    coverSrc: "/images/places/19.jpg",
    rating: 4,
    price: 4277
  },
  {
    id: 178,
    title: "Redhold",
    noodbed: 4,
    bathroom: 2,
    area: 39,
    avaible: false,
    county: "Canada",
    address: "39706 Milwaukee Hill",
    category: "Cottage",
    coverSrc: "/images/places/35.jpg",
    rating: 1,
    price: 4414
  },
  {
    id: 179,
    title: "Zamit",
    noodbed: 4,
    bathroom: 2,
    area: 57,
    avaible: false,
    county: "Germany",
    address: "6746 Drewry Plaza",
    category: "House",
    coverSrc: "/images/places/43.jpg",
    rating: 3,
    price: 3284
  },
  {
    id: 180,
    title: "Namfix",
    noodbed: 2,
    bathroom: 3,
    area: 33,
    avaible: true,
    county: "United States",
    address: "0901 Leroy Street",
    category: "Cottage",
    coverSrc: "/images/places/45.jpg",
    rating: 5,
    price: 1201
  },
  {
    id: 181,
    title: "Latlux",
    noodbed: 2,
    bathroom: 2,
    area: 12,
    avaible: true,
    county: "Australia",
    address: "54498 Artisan Place",
    category: "Hotel",
    coverSrc: "/images/places/21.jpg",
    rating: 5,
    price: 4958
  },
  {
    id: 182,
    title: "Flowdesk",
    noodbed: 1,
    bathroom: 3,
    area: 22,
    avaible: false,
    county: "Australia",
    address: "15441 Quincy Road",
    category: "Villa",
    coverSrc: "/images/places/25.jpg",
    rating: 4,
    price: 4662
  },
  {
    id: 183,
    title: "Matsoft",
    noodbed: 1,
    bathroom: 1,
    area: 34,
    avaible: true,
    county: "Canada",
    address: "917 Troy Point",
    category: "Apartment",
    coverSrc: "/images/places/17.jpg",
    rating: 2,
    price: 2299
  },
  {
    id: 184,
    title: "Cardguard",
    noodbed: 4,
    bathroom: 2,
    area: 93,
    avaible: true,
    county: "Australia",
    address: "9722 Basil Plaza",
    category: "Villa",
    coverSrc: "/images/places/1.jpg",
    rating: 2,
    price: 1564
  },
  {
    id: 185,
    title: "Gembucket",
    noodbed: 3,
    bathroom: 3,
    area: 21,
    avaible: true,
    county: "Australia",
    address: "57485 Hanover Road",
    category: "Apartment",
    coverSrc: "/images/places/19.jpg",
    rating: 1,
    price: 3265
  },
  {
    id: 186,
    title: "Cookley",
    noodbed: 1,
    bathroom: 1,
    area: 58,
    avaible: false,
    county: "Germany",
    address: "8 Tomscot Terrace",
    category: "Lounge",
    coverSrc: "/images/places/45.jpg",
    rating: 5,
    price: 1798
  },
  {
    id: 187,
    title: "Pannier",
    noodbed: 1,
    bathroom: 1,
    area: 44,
    avaible: false,
    county: "France",
    address: "095 Katie Plaza",
    category: "Hotel",
    coverSrc: "/images/places/10.jpg",
    rating: 5,
    price: 1795
  },
  {
    id: 188,
    title: "Temp",
    noodbed: 4,
    bathroom: 2,
    area: 77,
    avaible: true,
    county: "Germany",
    address: "0 School Trail",
    category: "Hostel",
    coverSrc: "/images/places/1.jpg",
    rating: 5,
    price: 1454
  },
  {
    id: 189,
    title: "Vagram",
    noodbed: 2,
    bathroom: 1,
    area: 64,
    avaible: true,
    county: "Japan",
    address: "1832 Blackbird Court",
    category: "Apartment",
    coverSrc: "/images/places/12.jpg",
    rating: 4,
    price: 1688
  },
  {
    id: 190,
    title: "Cardguard",
    noodbed: 4,
    bathroom: 1,
    area: 3,
    avaible: false,
    county: "Australia",
    address: "17 Tomscot Court",
    category: "Apartment",
    coverSrc: "/images/places/37.jpg",
    rating: 3,
    price: 3479
  },
  {
    id: 191,
    title: "Daltfresh",
    noodbed: 4,
    bathroom: 2,
    area: 4,
    avaible: true,
    county: "Australia",
    address: "05 Aberg Way",
    category: "Hotel",
    coverSrc: "/images/places/46.jpg",
    rating: 2,
    price: 1590
  },
  {
    id: 192,
    title: "Treeflex",
    noodbed: 2,
    bathroom: 2,
    area: 23,
    avaible: true,
    county: "France",
    address: "00137 Farmco Road",
    category: "Apartment",
    coverSrc: "/images/places/26.jpg",
    rating: 5,
    price: 2383
  },
  {
    id: 193,
    title: "Asoka",
    noodbed: 4,
    bathroom: 3,
    area: 88,
    avaible: true,
    county: "France",
    address: "2473 Westport Plaza",
    category: "House",
    coverSrc: "/images/places/15.jpg",
    rating: 1,
    price: 2166
  },
  {
    id: 194,
    title: "Redhold",
    noodbed: 1,
    bathroom: 2,
    area: 42,
    avaible: false,
    county: "Canada",
    address: "23420 Pankratz Place",
    category: "Motel",
    coverSrc: "/images/places/30.jpg",
    rating: 2,
    price: 3250
  },
  {
    id: 195,
    title: "Ventosanzap",
    noodbed: 4,
    bathroom: 1,
    area: 81,
    avaible: false,
    county: "Canada",
    address: "6697 Victoria Street",
    category: "Villa",
    coverSrc: "/images/places/30.jpg",
    rating: 4,
    price: 2629
  },
  {
    id: 196,
    title: "Trippledex",
    noodbed: 2,
    bathroom: 3,
    area: 63,
    avaible: true,
    county: "Canada",
    address: "427 Tennessee Avenue",
    category: "Motel",
    coverSrc: "/images/places/7.jpg",
    rating: 5,
    price: 1006
  },
  {
    id: 197,
    title: "Keylex",
    noodbed: 1,
    bathroom: 2,
    area: 57,
    avaible: true,
    county: "Canada",
    address: "1 Carioca Road",
    category: "Lounge",
    coverSrc: "/images/places/4.jpg",
    rating: 1,
    price: 2512
  },
  {
    id: 198,
    title: "Vagram",
    noodbed: 3,
    bathroom: 1,
    area: 22,
    avaible: true,
    county: "United States",
    address: "6 Mifflin Parkway",
    category: "Cottage",
    coverSrc: "/images/places/28.jpg",
    rating: 5,
    price: 3291
  },
  {
    id: 199,
    title: "Voyatouch",
    noodbed: 3,
    bathroom: 3,
    area: 69,
    avaible: false,
    county: "Canada",
    address: "8 Linden Park",
    category: "House",
    coverSrc: "/images/places/4.jpg",
    rating: 1,
    price: 1056
  },
  {
    id: 200,
    title: "Span",
    noodbed: 3,
    bathroom: 2,
    area: 39,
    avaible: false,
    county: "Canada",
    address: "61251 Towne Terrace",
    category: "Motel",
    coverSrc: "/images/places/9.jpg",
    rating: 3,
    price: 4895
  },
  {
    id: 201,
    title: "Kanlam",
    noodbed: 1,
    bathroom: 2,
    area: 37,
    avaible: true,
    county: "Canada",
    address: "9132 Mosinee Hill",
    category: "Motel",
    coverSrc: "/images/places/23.jpg",
    rating: 5,
    price: 4742
  },
  {
    id: 202,
    title: "Job",
    noodbed: 2,
    bathroom: 3,
    area: 95,
    avaible: false,
    county: "Germany",
    address: "79 Paget Circle",
    category: "Farm House",
    coverSrc: "/images/places/27.jpg",
    rating: 4,
    price: 1942
  },
  {
    id: 203,
    title: "Sub-Ex",
    noodbed: 3,
    bathroom: 2,
    area: 86,
    avaible: false,
    county: "Japan",
    address: "254 Holy Cross Circle",
    category: "Farm House",
    coverSrc: "/images/places/26.jpg",
    rating: 4,
    price: 1753
  },
  {
    id: 204,
    title: "Cardguard",
    noodbed: 3,
    bathroom: 2,
    area: 86,
    avaible: true,
    county: "Japan",
    address: "16027 Barnett Crossing",
    category: "House",
    coverSrc: "/images/places/28.jpg",
    rating: 2,
    price: 1491
  },
  {
    id: 205,
    title: "Cardguard",
    noodbed: 4,
    bathroom: 1,
    area: 60,
    avaible: false,
    county: "France",
    address: "34 Lillian Pass",
    category: "Motel",
    coverSrc: "/images/places/4.jpg",
    rating: 1,
    price: 2641
  },
  {
    id: 206,
    title: "Namfix",
    noodbed: 3,
    bathroom: 2,
    area: 72,
    avaible: true,
    county: "Australia",
    address: "7291 Buell Pass",
    category: "Apartment",
    coverSrc: "/images/places/7.jpg",
    rating: 4,
    price: 1045
  },
  {
    id: 207,
    title: "Stim",
    noodbed: 1,
    bathroom: 1,
    area: 80,
    avaible: false,
    county: "Australia",
    address: "1 Pierstorff Crossing",
    category: "Villa",
    coverSrc: "/images/places/5.jpg",
    rating: 3,
    price: 4651
  },
  {
    id: 208,
    title: "Overhold",
    noodbed: 4,
    bathroom: 2,
    area: 45,
    avaible: true,
    county: "France",
    address: "2 Oak Alley",
    category: "Motel",
    coverSrc: "/images/places/18.jpg",
    rating: 3,
    price: 1246
  },
  {
    id: 209,
    title: "Voyatouch",
    noodbed: 4,
    bathroom: 3,
    area: 81,
    avaible: true,
    county: "France",
    address: "71 Hazelcrest Alley",
    category: "Hostel",
    coverSrc: "/images/places/12.jpg",
    rating: 5,
    price: 1126
  },
  {
    id: 210,
    title: "Y-Solowarm",
    noodbed: 4,
    bathroom: 1,
    area: 85,
    avaible: false,
    county: "Japan",
    address: "77646 Sage Junction",
    category: "Villa",
    coverSrc: "/images/places/42.jpg",
    rating: 3,
    price: 1191
  },
  {
    id: 211,
    title: "Lotlux",
    noodbed: 4,
    bathroom: 2,
    area: 20,
    avaible: false,
    county: "India",
    address: "33375 Rowland Crossing",
    category: "Villa",
    coverSrc: "/images/places/46.jpg",
    rating: 1,
    price: 3123
  },
  {
    id: 212,
    title: "Domainer",
    noodbed: 1,
    bathroom: 2,
    area: 75,
    avaible: false,
    county: "Canada",
    address: "98022 Hoffman Street",
    category: "Cottage",
    coverSrc: "/images/places/39.jpg",
    rating: 3,
    price: 2386
  },
  {
    id: 213,
    title: "Cardify",
    noodbed: 2,
    bathroom: 3,
    area: 93,
    avaible: false,
    county: "France",
    address: "13 Helena Way",
    category: "Hotel",
    coverSrc: "/images/places/29.jpg",
    rating: 5,
    price: 1982
  },
  {
    id: 214,
    title: "Stronghold",
    noodbed: 3,
    bathroom: 3,
    area: 14,
    avaible: false,
    county: "United States",
    address: "51 Hermina Plaza",
    category: "Motel",
    coverSrc: "/images/places/34.jpg",
    rating: 5,
    price: 1376
  },
  {
    id: 215,
    title: "Bytecard",
    noodbed: 2,
    bathroom: 2,
    area: 22,
    avaible: false,
    county: "United States",
    address: "4 Sheridan Crossing",
    category: "Farm House",
    coverSrc: "/images/places/18.jpg",
    rating: 4,
    price: 1317
  },
  {
    id: 216,
    title: "Overhold",
    noodbed: 3,
    bathroom: 2,
    area: 78,
    avaible: true,
    county: "United States",
    address: "46 Manufacturers Center",
    category: "Hostel",
    coverSrc: "/images/places/25.jpg",
    rating: 2,
    price: 1069
  },
  {
    id: 217,
    title: "Voltsillam",
    noodbed: 3,
    bathroom: 2,
    area: 57,
    avaible: false,
    county: "United States",
    address: "5 Oak Valley Circle",
    category: "Cottage",
    coverSrc: "/images/places/43.jpg",
    rating: 4,
    price: 4401
  },
  {
    id: 218,
    title: "Bytecard",
    noodbed: 2,
    bathroom: 3,
    area: 25,
    avaible: true,
    county: "France",
    address: "690 Mifflin Hill",
    category: "Farm House",
    coverSrc: "/images/places/28.jpg",
    rating: 1,
    price: 1965
  },
  {
    id: 219,
    title: "Cardguard",
    noodbed: 3,
    bathroom: 2,
    area: 67,
    avaible: true,
    county: "Germany",
    address: "302 Victoria Crossing",
    category: "Hotel",
    coverSrc: "/images/places/24.jpg",
    rating: 3,
    price: 3451
  },
  {
    id: 220,
    title: "Zamit",
    noodbed: 3,
    bathroom: 1,
    area: 48,
    avaible: true,
    county: "Germany",
    address: "84 Kenwood Court",
    category: "Lounge",
    coverSrc: "/images/places/19.jpg",
    rating: 3,
    price: 4925
  },
  {
    id: 221,
    title: "Fix San",
    noodbed: 1,
    bathroom: 1,
    area: 8,
    avaible: true,
    county: "Canada",
    address: "64861 Grim Court",
    category: "Lounge",
    coverSrc: "/images/places/26.jpg",
    rating: 1,
    price: 4507
  },
  {
    id: 222,
    title: "Redhold",
    noodbed: 2,
    bathroom: 1,
    area: 62,
    avaible: false,
    county: "Germany",
    address: "2 Summer Ridge Parkway",
    category: "Lounge",
    coverSrc: "/images/places/11.jpg",
    rating: 5,
    price: 1475
  },
  {
    id: 223,
    title: "Daltfresh",
    noodbed: 3,
    bathroom: 2,
    area: 40,
    avaible: true,
    county: "United States",
    address: "80379 Fisk Avenue",
    category: "Hostel",
    coverSrc: "/images/places/20.jpg",
    rating: 4,
    price: 1526
  },
  {
    id: 224,
    title: "Wrapsafe",
    noodbed: 3,
    bathroom: 2,
    area: 47,
    avaible: false,
    county: "Australia",
    address: "8 Commercial Avenue",
    category: "Motel",
    coverSrc: "/images/places/44.jpg",
    rating: 3,
    price: 4768
  },
  {
    id: 225,
    title: "Lotlux",
    noodbed: 1,
    bathroom: 1,
    area: 4,
    avaible: true,
    county: "India",
    address: "7 Linden Point",
    category: "Hostel",
    coverSrc: "/images/places/30.jpg",
    rating: 4,
    price: 2455
  },
  {
    id: 226,
    title: "Regrant",
    noodbed: 1,
    bathroom: 2,
    area: 74,
    avaible: false,
    county: "France",
    address: "34547 Duke Drive",
    category: "Motel",
    coverSrc: "/images/places/4.jpg",
    rating: 1,
    price: 1290
  },
  {
    id: 227,
    title: "Regrant",
    noodbed: 1,
    bathroom: 3,
    area: 40,
    avaible: false,
    county: "Canada",
    address: "1 Starling Plaza",
    category: "Motel",
    coverSrc: "/images/places/9.jpg",
    rating: 4,
    price: 4307
  },
  {
    id: 228,
    title: "Regrant",
    noodbed: 4,
    bathroom: 1,
    area: 96,
    avaible: true,
    county: "France",
    address: "89 Reinke Terrace",
    category: "Villa",
    coverSrc: "/images/places/16.jpg",
    rating: 1,
    price: 4623
  },
  {
    id: 229,
    title: "Latlux",
    noodbed: 4,
    bathroom: 1,
    area: 70,
    avaible: true,
    county: "France",
    address: "872 Chive Junction",
    category: "Farm House",
    coverSrc: "/images/places/35.jpg",
    rating: 2,
    price: 3006
  },
  {
    id: 230,
    title: "Domainer",
    noodbed: 1,
    bathroom: 1,
    area: 78,
    avaible: true,
    county: "United States",
    address: "64 Manley Drive",
    category: "Cottage",
    coverSrc: "/images/places/43.jpg",
    rating: 3,
    price: 3670
  },
  {
    id: 231,
    title: "Bamity",
    noodbed: 3,
    bathroom: 2,
    area: 76,
    avaible: true,
    county: "India",
    address: "944 Green Ridge Park",
    category: "Hotel",
    coverSrc: "/images/places/4.jpg",
    rating: 5,
    price: 4989
  },
  {
    id: 232,
    title: "Matsoft",
    noodbed: 1,
    bathroom: 3,
    area: 71,
    avaible: false,
    county: "Japan",
    address: "5 Harbort Pass",
    category: "Apartment",
    coverSrc: "/images/places/45.jpg",
    rating: 5,
    price: 1179
  },
  {
    id: 233,
    title: "Lotlux",
    noodbed: 4,
    bathroom: 2,
    area: 78,
    avaible: true,
    county: "Japan",
    address: "8 Macpherson Plaza",
    category: "Apartment",
    coverSrc: "/images/places/43.jpg",
    rating: 5,
    price: 1362
  },
  {
    id: 234,
    title: "Aerified",
    noodbed: 1,
    bathroom: 3,
    area: 53,
    avaible: false,
    county: "Australia",
    address: "25946 Johnson Lane",
    category: "Motel",
    coverSrc: "/images/places/8.jpg",
    rating: 2,
    price: 4791
  },
  {
    id: 235,
    title: "Daltfresh",
    noodbed: 3,
    bathroom: 1,
    area: 62,
    avaible: false,
    county: "United States",
    address: "3729 Anzinger Park",
    category: "Lounge",
    coverSrc: "/images/places/28.jpg",
    rating: 1,
    price: 2671
  },
  {
    id: 236,
    title: "Tin",
    noodbed: 2,
    bathroom: 1,
    area: 61,
    avaible: true,
    county: "Australia",
    address: "51 Talisman Way",
    category: "Motel",
    coverSrc: "/images/places/34.jpg",
    rating: 5,
    price: 1967
  },
  {
    id: 237,
    title: "Keylex",
    noodbed: 1,
    bathroom: 2,
    area: 51,
    avaible: true,
    county: "Germany",
    address: "61 Hudson Point",
    category: "Cottage",
    coverSrc: "/images/places/11.jpg",
    rating: 4,
    price: 1538
  },
  {
    id: 238,
    title: "Biodex",
    noodbed: 4,
    bathroom: 1,
    area: 21,
    avaible: false,
    county: "United States",
    address: "4597 Weeping Birch Road",
    category: "House",
    coverSrc: "/images/places/2.jpg",
    rating: 5,
    price: 1880
  },
  {
    id: 239,
    title: "Zathin",
    noodbed: 2,
    bathroom: 3,
    area: 48,
    avaible: true,
    county: "India",
    address: "29303 Merchant Court",
    category: "Lounge",
    coverSrc: "/images/places/30.jpg",
    rating: 4,
    price: 3504
  },
  {
    id: 240,
    title: "Ronstring",
    noodbed: 1,
    bathroom: 2,
    area: 77,
    avaible: true,
    county: "United States",
    address: "6652 Hayes Junction",
    category: "Motel",
    coverSrc: "/images/places/14.jpg",
    rating: 1,
    price: 3552
  },
  {
    id: 241,
    title: "Span",
    noodbed: 2,
    bathroom: 2,
    area: 90,
    avaible: false,
    county: "Australia",
    address: "937 1st Hill",
    category: "Cottage",
    coverSrc: "/images/places/33.jpg",
    rating: 4,
    price: 3090
  },
  {
    id: 242,
    title: "Home Ing",
    noodbed: 4,
    bathroom: 2,
    area: 14,
    avaible: true,
    county: "Canada",
    address: "960 Fairview Park",
    category: "House",
    coverSrc: "/images/places/16.jpg",
    rating: 1,
    price: 2798
  },
  {
    id: 243,
    title: "Holdlamis",
    noodbed: 2,
    bathroom: 3,
    area: 79,
    avaible: true,
    county: "France",
    address: "8973 Forest Junction",
    category: "Hostel",
    coverSrc: "/images/places/34.jpg",
    rating: 1,
    price: 1407
  },
  {
    id: 244,
    title: "Zontrax",
    noodbed: 4,
    bathroom: 3,
    area: 89,
    avaible: false,
    county: "Australia",
    address: "2 Bay Trail",
    category: "Cottage",
    coverSrc: "/images/places/38.jpg",
    rating: 1,
    price: 2988
  },
  {
    id: 245,
    title: "Alphazap",
    noodbed: 1,
    bathroom: 2,
    area: 33,
    avaible: true,
    county: "Canada",
    address: "460 Shoshone Place",
    category: "Lounge",
    coverSrc: "/images/places/21.jpg",
    rating: 1,
    price: 1873
  },
  {
    id: 246,
    title: "Cardify",
    noodbed: 2,
    bathroom: 2,
    area: 49,
    avaible: true,
    county: "Australia",
    address: "53 Hermina Place",
    category: "Villa",
    coverSrc: "/images/places/9.jpg",
    rating: 3,
    price: 2429
  },
  {
    id: 247,
    title: "Fix San",
    noodbed: 3,
    bathroom: 2,
    area: 14,
    avaible: false,
    county: "Australia",
    address: "6173 Golf View Crossing",
    category: "Hotel",
    coverSrc: "/images/places/36.jpg",
    rating: 1,
    price: 1896
  },
  {
    id: 248,
    title: "Kanlam",
    noodbed: 1,
    bathroom: 2,
    area: 83,
    avaible: false,
    county: "United States",
    address: "3 Coolidge Place",
    category: "Hostel",
    coverSrc: "/images/places/1.jpg",
    rating: 5,
    price: 1052
  },
  {
    id: 249,
    title: "Job",
    noodbed: 3,
    bathroom: 2,
    area: 10,
    avaible: false,
    county: "France",
    address: "0 Pond Drive",
    category: "Cottage",
    coverSrc: "/images/places/17.jpg",
    rating: 1,
    price: 1678
  },
  {
    id: 250,
    title: "Sub-Ex",
    noodbed: 3,
    bathroom: 1,
    area: 67,
    avaible: false,
    county: "Canada",
    address: "4957 Quincy Place",
    category: "Hotel",
    coverSrc: "/images/places/31.jpg",
    rating: 5,
    price: 1939
  },
  {
    id: 251,
    title: "Rank",
    noodbed: 3,
    bathroom: 3,
    area: 67,
    avaible: false,
    county: "United States",
    address: "1409 Wayridge Alley",
    category: "Lounge",
    coverSrc: "/images/places/40.jpg",
    rating: 4,
    price: 4575
  },
  {
    id: 252,
    title: "Bamity",
    noodbed: 3,
    bathroom: 2,
    area: 20,
    avaible: true,
    county: "United States",
    address: "91398 Surrey Trail",
    category: "Cottage",
    coverSrc: "/images/places/30.jpg",
    rating: 3,
    price: 4863
  },
  {
    id: 253,
    title: "Zontrax",
    noodbed: 4,
    bathroom: 3,
    area: 33,
    avaible: true,
    county: "Australia",
    address: "49499 Cardinal Court",
    category: "Farm House",
    coverSrc: "/images/places/8.jpg",
    rating: 2,
    price: 4020
  },
  {
    id: 254,
    title: "Prodder",
    noodbed: 2,
    bathroom: 3,
    area: 13,
    avaible: false,
    county: "Canada",
    address: "71 Boyd Park",
    category: "House",
    coverSrc: "/images/places/39.jpg",
    rating: 5,
    price: 1459
  },
  {
    id: 255,
    title: "Lotstring",
    noodbed: 1,
    bathroom: 2,
    area: 25,
    avaible: false,
    county: "Australia",
    address: "70687 Mallory Place",
    category: "Motel",
    coverSrc: "/images/places/37.jpg",
    rating: 4,
    price: 2135
  },
  {
    id: 256,
    title: "Lotstring",
    noodbed: 1,
    bathroom: 2,
    area: 99,
    avaible: false,
    county: "France",
    address: "79391 West Avenue",
    category: "Cottage",
    coverSrc: "/images/places/7.jpg",
    rating: 1,
    price: 1103
  },
  {
    id: 257,
    title: "Quo Lux",
    noodbed: 3,
    bathroom: 2,
    area: 60,
    avaible: false,
    county: "India",
    address: "4 Northland Court",
    category: "Lounge",
    coverSrc: "/images/places/28.jpg",
    rating: 3,
    price: 2226
  },
  {
    id: 258,
    title: "Y-find",
    noodbed: 4,
    bathroom: 1,
    area: 39,
    avaible: true,
    county: "Australia",
    address: "84 Utah Alley",
    category: "Apartment",
    coverSrc: "/images/places/41.jpg",
    rating: 2,
    price: 2396
  },
  {
    id: 259,
    title: "Keylex",
    noodbed: 1,
    bathroom: 1,
    area: 37,
    avaible: true,
    county: "India",
    address: "582 Fieldstone Alley",
    category: "Motel",
    coverSrc: "/images/places/15.jpg",
    rating: 4,
    price: 3005
  },
  {
    id: 260,
    title: "Flowdesk",
    noodbed: 4,
    bathroom: 3,
    area: 43,
    avaible: false,
    county: "Germany",
    address: "13 New Castle Crossing",
    category: "Hotel",
    coverSrc: "/images/places/7.jpg",
    rating: 1,
    price: 1973
  },
  {
    id: 261,
    title: "Rank",
    noodbed: 4,
    bathroom: 2,
    area: 90,
    avaible: false,
    county: "India",
    address: "5 Old Shore Street",
    category: "Farm House",
    coverSrc: "/images/places/34.jpg",
    rating: 2,
    price: 4207
  },
  {
    id: 262,
    title: "Zoolab",
    noodbed: 3,
    bathroom: 2,
    area: 23,
    avaible: false,
    county: "Australia",
    address: "7012 Rieder Drive",
    category: "Motel",
    coverSrc: "/images/places/33.jpg",
    rating: 3,
    price: 3605
  },
  {
    id: 263,
    title: "Job",
    noodbed: 4,
    bathroom: 2,
    area: 73,
    avaible: false,
    county: "India",
    address: "9493 Artisan Hill",
    category: "Hostel",
    coverSrc: "/images/places/16.jpg",
    rating: 1,
    price: 1841
  },
  {
    id: 264,
    title: "Sonsing",
    noodbed: 3,
    bathroom: 2,
    area: 89,
    avaible: true,
    county: "United States",
    address: "2918 Nevada Terrace",
    category: "House",
    coverSrc: "/images/places/42.jpg",
    rating: 5,
    price: 2357
  },
  {
    id: 265,
    title: "Bitwolf",
    noodbed: 2,
    bathroom: 2,
    area: 34,
    avaible: true,
    county: "Germany",
    address: "94 Elmside Avenue",
    category: "Farm House",
    coverSrc: "/images/places/21.jpg",
    rating: 2,
    price: 2304
  },
  {
    id: 266,
    title: "Zaam-Dox",
    noodbed: 2,
    bathroom: 2,
    area: 79,
    avaible: true,
    county: "France",
    address: "99 Sullivan Road",
    category: "Hostel",
    coverSrc: "/images/places/17.jpg",
    rating: 3,
    price: 3015
  },
  {
    id: 267,
    title: "Mat Lam Tam",
    noodbed: 2,
    bathroom: 1,
    area: 27,
    avaible: false,
    county: "Australia",
    address: "766 Golf Course Lane",
    category: "Cottage",
    coverSrc: "/images/places/41.jpg",
    rating: 3,
    price: 1578
  },
  {
    id: 268,
    title: "Tampflex",
    noodbed: 4,
    bathroom: 2,
    area: 26,
    avaible: false,
    county: "Germany",
    address: "0355 Hooker Road",
    category: "Hotel",
    coverSrc: "/images/places/36.jpg",
    rating: 4,
    price: 4958
  },
  {
    id: 269,
    title: "Flexidy",
    noodbed: 4,
    bathroom: 2,
    area: 32,
    avaible: false,
    county: "Australia",
    address: "25388 Elka Center",
    category: "Hostel",
    coverSrc: "/images/places/12.jpg",
    rating: 2,
    price: 3433
  },
  {
    id: 270,
    title: "Y-find",
    noodbed: 3,
    bathroom: 1,
    area: 1,
    avaible: false,
    county: "Germany",
    address: "26839 Macpherson Alley",
    category: "Cottage",
    coverSrc: "/images/places/15.jpg",
    rating: 1,
    price: 3754
  },
  {
    id: 271,
    title: "Holdlamis",
    noodbed: 2,
    bathroom: 1,
    area: 26,
    avaible: true,
    county: "United States",
    address: "71325 Summer Ridge Alley",
    category: "Villa",
    coverSrc: "/images/places/18.jpg",
    rating: 2,
    price: 4084
  },
  {
    id: 272,
    title: "Rank",
    noodbed: 4,
    bathroom: 3,
    area: 50,
    avaible: false,
    county: "Australia",
    address: "26488 Main Park",
    category: "Motel",
    coverSrc: "/images/places/18.jpg",
    rating: 4,
    price: 4148
  },
  {
    id: 273,
    title: "Zaam-Dox",
    noodbed: 4,
    bathroom: 3,
    area: 90,
    avaible: true,
    county: "India",
    address: "7767 Mesta Trail",
    category: "Hostel",
    coverSrc: "/images/places/39.jpg",
    rating: 3,
    price: 4460
  },
  {
    id: 274,
    title: "Fix San",
    noodbed: 4,
    bathroom: 1,
    area: 60,
    avaible: true,
    county: "France",
    address: "7 Golf Course Place",
    category: "Hostel",
    coverSrc: "/images/places/39.jpg",
    rating: 4,
    price: 4364
  },
  {
    id: 275,
    title: "Prodder",
    noodbed: 4,
    bathroom: 3,
    area: 67,
    avaible: false,
    county: "United States",
    address: "926 Northwestern Trail",
    category: "Cottage",
    coverSrc: "/images/places/10.jpg",
    rating: 3,
    price: 2600
  },
  {
    id: 276,
    title: "Solarbreeze",
    noodbed: 3,
    bathroom: 3,
    area: 32,
    avaible: false,
    county: "Canada",
    address: "74316 Lotheville Trail",
    category: "Lounge",
    coverSrc: "/images/places/29.jpg",
    rating: 4,
    price: 4517
  },
  {
    id: 277,
    title: "Tresom",
    noodbed: 2,
    bathroom: 1,
    area: 4,
    avaible: true,
    county: "Australia",
    address: "7 Swallow Street",
    category: "Motel",
    coverSrc: "/images/places/44.jpg",
    rating: 4,
    price: 3036
  },
  {
    id: 278,
    title: "Zaam-Dox",
    noodbed: 1,
    bathroom: 3,
    area: 17,
    avaible: false,
    county: "Canada",
    address: "52 Northwestern Street",
    category: "Apartment",
    coverSrc: "/images/places/12.jpg",
    rating: 2,
    price: 2588
  },
  {
    id: 279,
    title: "Latlux",
    noodbed: 2,
    bathroom: 1,
    area: 23,
    avaible: false,
    county: "United States",
    address: "93 Pleasure Terrace",
    category: "Villa",
    coverSrc: "/images/places/38.jpg",
    rating: 2,
    price: 1027
  },
  {
    id: 280,
    title: "Asoka",
    noodbed: 1,
    bathroom: 2,
    area: 39,
    avaible: true,
    county: "Germany",
    address: "35198 Kennedy Pass",
    category: "Lounge",
    coverSrc: "/images/places/36.jpg",
    rating: 2,
    price: 2865
  },
  {
    id: 281,
    title: "Matsoft",
    noodbed: 2,
    bathroom: 3,
    area: 92,
    avaible: false,
    county: "Japan",
    address: "4241 Beilfuss Road",
    category: "Apartment",
    coverSrc: "/images/places/2.jpg",
    rating: 4,
    price: 1754
  },
  {
    id: 282,
    title: "Zathin",
    noodbed: 3,
    bathroom: 2,
    area: 60,
    avaible: false,
    county: "Australia",
    address: "4865 New Castle Center",
    category: "Motel",
    coverSrc: "/images/places/45.jpg",
    rating: 1,
    price: 3833
  },
  {
    id: 283,
    title: "Tin",
    noodbed: 3,
    bathroom: 1,
    area: 45,
    avaible: true,
    county: "Germany",
    address: "39628 Burrows Plaza",
    category: "Hostel",
    coverSrc: "/images/places/44.jpg",
    rating: 1,
    price: 4200
  },
  {
    id: 284,
    title: "Mat Lam Tam",
    noodbed: 2,
    bathroom: 1,
    area: 65,
    avaible: true,
    county: "United States",
    address: "2 Stone Corner Crossing",
    category: "Hotel",
    coverSrc: "/images/places/26.jpg",
    rating: 1,
    price: 4276
  },
  {
    id: 285,
    title: "Y-find",
    noodbed: 4,
    bathroom: 3,
    area: 5,
    avaible: false,
    county: "United States",
    address: "64 Kropf Road",
    category: "Cottage",
    coverSrc: "/images/places/14.jpg",
    rating: 4,
    price: 4864
  },
  {
    id: 286,
    title: "Job",
    noodbed: 4,
    bathroom: 3,
    area: 29,
    avaible: false,
    county: "India",
    address: "66692 Montana Parkway",
    category: "Motel",
    coverSrc: "/images/places/37.jpg",
    rating: 1,
    price: 3924
  },
  {
    id: 287,
    title: "Voyatouch",
    noodbed: 4,
    bathroom: 2,
    area: 8,
    avaible: true,
    county: "Australia",
    address: "7 Crowley Hill",
    category: "Hotel",
    coverSrc: "/images/places/11.jpg",
    rating: 5,
    price: 2987
  },
  {
    id: 288,
    title: "Bigtax",
    noodbed: 4,
    bathroom: 2,
    area: 19,
    avaible: false,
    county: "United States",
    address: "7729 Chinook Drive",
    category: "Cottage",
    coverSrc: "/images/places/39.jpg",
    rating: 2,
    price: 4801
  },
  {
    id: 289,
    title: "Mat Lam Tam",
    noodbed: 1,
    bathroom: 2,
    area: 43,
    avaible: true,
    county: "Canada",
    address: "4580 4th Park",
    category: "Villa",
    coverSrc: "/images/places/27.jpg",
    rating: 3,
    price: 1077
  },
  {
    id: 290,
    title: "Ventosanzap",
    noodbed: 1,
    bathroom: 2,
    area: 42,
    avaible: true,
    county: "Australia",
    address: "1 Forest Trail",
    category: "Hotel",
    coverSrc: "/images/places/36.jpg",
    rating: 3,
    price: 2757
  },
  {
    id: 291,
    title: "Zamit",
    noodbed: 2,
    bathroom: 1,
    area: 18,
    avaible: true,
    county: "India",
    address: "50797 Randy Parkway",
    category: "Apartment",
    coverSrc: "/images/places/25.jpg",
    rating: 1,
    price: 2601
  },
  {
    id: 292,
    title: "Rank",
    noodbed: 4,
    bathroom: 2,
    area: 52,
    avaible: false,
    county: "India",
    address: "52 Tony Trail",
    category: "Apartment",
    coverSrc: "/images/places/9.jpg",
    rating: 1,
    price: 1168
  },
  {
    id: 293,
    title: "Redhold",
    noodbed: 2,
    bathroom: 2,
    area: 13,
    avaible: true,
    county: "United States",
    address: "5 Dayton Circle",
    category: "Farm House",
    coverSrc: "/images/places/2.jpg",
    rating: 5,
    price: 3512
  },
  {
    id: 294,
    title: "Sonsing",
    noodbed: 4,
    bathroom: 2,
    area: 51,
    avaible: false,
    county: "Japan",
    address: "5579 Golf Course Street",
    category: "Hotel",
    coverSrc: "/images/places/27.jpg",
    rating: 2,
    price: 3669
  },
  {
    id: 295,
    title: "Prodder",
    noodbed: 1,
    bathroom: 3,
    area: 5,
    avaible: true,
    county: "India",
    address: "25935 Dixon Hill",
    category: "Hotel",
    coverSrc: "/images/places/40.jpg",
    rating: 2,
    price: 1858
  },
  {
    id: 296,
    title: "Matsoft",
    noodbed: 1,
    bathroom: 3,
    area: 89,
    avaible: true,
    county: "Canada",
    address: "3982 Rockefeller Street",
    category: "Villa",
    coverSrc: "/images/places/2.jpg",
    rating: 1,
    price: 1362
  },
  {
    id: 297,
    title: "Opela",
    noodbed: 1,
    bathroom: 2,
    area: 33,
    avaible: true,
    county: "Germany",
    address: "547 Hauk Plaza",
    category: "Motel",
    coverSrc: "/images/places/40.jpg",
    rating: 5,
    price: 1137
  },
  {
    id: 298,
    title: "Matsoft",
    noodbed: 3,
    bathroom: 3,
    area: 67,
    avaible: true,
    county: "France",
    address: "6897 Vidon Drive",
    category: "House",
    coverSrc: "/images/places/32.jpg",
    rating: 2,
    price: 3467
  },
  {
    id: 299,
    title: "Rank",
    noodbed: 1,
    bathroom: 2,
    area: 85,
    avaible: true,
    county: "Canada",
    address: "8092 Golf View Point",
    category: "Farm House",
    coverSrc: "/images/places/27.jpg",
    rating: 3,
    price: 1729
  },
  {
    id: 300,
    title: "Cookley",
    noodbed: 3,
    bathroom: 3,
    area: 80,
    avaible: false,
    county: "France",
    address: "779 Ridgeview Circle",
    category: "Apartment",
    coverSrc: "/images/places/28.jpg",
    rating: 3,
    price: 4328
  }
]
